# Generated by Django 3.2.9 on 2022-01-08 11:37

from django.db import migrations
import user.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_newuser_created_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
                ('objects', user.manager.CustomUserManager()),
            ],
        ),
    ]
